# Generated by Django 3.2 on 2021-04-18 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GeoLocationModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plantation_height", models.FloatField()),
                ("longitude", models.FloatField()),
                ("latitude", models.FloatField()),
                ("country", models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name="SensorialProfileModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accidity", models.FloatField()),
                ("balance", models.FloatField()),
                ("body", models.FloatField()),
                ("flavor", models.FloatField()),
                ("aftertaste", models.FloatField()),
                ("sweetness", models.FloatField()),
                ("clean_cup", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="PlantationModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                (
                    "geo_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="coffee.geolocationmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CoffeeModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("slug", models.CharField(max_length=80)),
                ("descrption", models.TextField(blank=True)),
                (
                    "processing_method",
                    models.CharField(
                        choices=[
                            ("washed", "Washed"),
                            ("dry", "Dry"),
                            ("natural", "Natural"),
                            ("honey", "Honey"),
                            ("unspecified", "Unspecified"),
                        ],
                        default="unspecified",
                        max_length=20,
                        verbose_name="ProcessingMethod",
                    ),
                ),
                ("roast_date", models.DateField()),
                (
                    "plantation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="coffee.plantationmodel",
                    ),
                ),
                (
                    "sensorial_profile",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="coffee.sensorialprofilemodel",
                    ),
                ),
            ],
        ),
    ]
