# Generated by Django 3.2 on 2021-04-22 18:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GeoLocationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plantation_height", models.FloatField()),
                ("longitude", models.FloatField()),
                ("latitude", models.FloatField()),
                ("country", models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name="SensorialProfileModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "accidity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxValueValidator(100)]
                    ),
                ),
                (
                    "balance",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxValueValidator(100)]
                    ),
                ),
                (
                    "body",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxValueValidator(100)]
                    ),
                ),
                (
                    "flavor",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxValueValidator(100)]
                    ),
                ),
                (
                    "aftertaste",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxValueValidator(100)]
                    ),
                ),
                (
                    "sweetness",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxValueValidator(100)]
                    ),
                ),
                (
                    "clean_cup",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxValueValidator(100)]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlantationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                (
                    "geo_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="coffee.geolocationmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CoffeeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("slug", models.CharField(max_length=80)),
                ("descrption", models.TextField(blank=True)),
                (
                    "processing_method",
                    models.CharField(
                        choices=[
                            ("washed", "Washed"),
                            ("dry", "Dry"),
                            ("natural", "Natural"),
                            ("honey", "Honey"),
                            ("unspecified", "Unspecified"),
                        ],
                        default="unspecified",
                        max_length=20,
                        verbose_name="ProcessingMethod",
                    ),
                ),
                ("roast_date", models.DateField()),
                (
                    "plantation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="coffee.plantationmodel",
                    ),
                ),
                (
                    "sensorial_profile",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="coffee.sensorialprofilemodel",
                    ),
                ),
            ],
        ),
    ]
