# Generated by Django 3.2 on 2021-04-25 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coffee", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="coffeemodel",
            old_name="descrption",
            new_name="description",
        ),
    ]
