# Generated by Django 3.2 on 2021-05-26 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ItemModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight", models.FloatField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "coffee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="coffee.coffeemodel",
                    ),
                ),
            ],
            options={
                "db_table": "item",
            },
        ),
    ]
