# Generated by Django 3.2 on 2021-06-06 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("coffee", "0002_rename_descrption_coffeemodel_description"),
        ("item", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemmodel",
            name="coffee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="coffee.coffeemodel"
            ),
        ),
    ]
